#!/bin/python
import sys
import re

tag_string = "autogenerated by cyrillic2c_hex - do not edit this comment!"
is_cyrline = re.compile("^\/\/CYRILLIC STRING \[(?P<strname>[^\]]*)\]=\[(?P<cyrstring>.*)\][^\]]*$")
is_autogen = re.compile(".*\/\/ "+tag_string+"$")

def cyr2hex(cyr_str):
    cyr_str_list = list(cyr_str.decode('utf-8').encode('cp1251'))
    result = ""
    for i in cyr_str_list:
        if ord(i) in range(0x80, 0xFF):
            result += "\\x"+format(ord(i),'x')
        else:
            result += i
    return result

out_file_list = []
with open(sys.argv[1],'r+') as f:
    for line in f:
        if not is_autogen.search(line):
            out_file_list.append(line)
        parsed_line = is_cyrline.search(line)
        if parsed_line:
            autogen_str = "#define "+(parsed_line.group('strname')+" \""+
                           cyr2hex(parsed_line.group('cyrstring'))+
                           "\" // "+tag_string+"\n" )
            out_file_list.append(autogen_str)
    f.seek(0)
    f.write("".join(out_file_list))
    f.truncate()

